### ISSUE TITLE
Web Components (Apa, Mengapa dan Bagaimana)?

### ISSUE THREAD

**Issue by kresnasatya** [BaliJS/talks#2]
Saya mau share materi seputar Web Components sesuai dengan judulnya di meetup Bali JS. Implementasinya mungkin akan saya berikan contoh dalam Vanilla, Polymer dan Stencil JS (bila memungkinkan).

Perkiraan akan share materi: April 2018.

Tantangan saat ini: masih cari waktu untuk menyusun slide dan mantapin nguasain materi yg dibawakan.

Trims.

**Comment by tvalentius** [comment]
Mantaap Sat 👍 

Misalkan dimajukan ke Februari or Maret gimana?

**Comment by kresnasatya** [comment]
Februari oke. Maret setelah nyepi ya maa.

**Comment by kresnasatya** [comment]
*mas.

On Feb 5, 2018 2:48 PM, satyakresna6295@gmail.com wrote:

Februari oke. Maret setelah nyepi ya maa.

On Feb 5, 2018 1:03 PM, "Trimikha Valentius" <notifications@github.com>
wrote:

Mantaap Sat 👍

Misalkan dimajukan ke Februari or Maret gimana?

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/BaliJS/talks/issues/2#issuecomment-362982410>, or mute
the thread

**Comment by kresnasatya** [comment]
Jadwal: 26 Feb 2018 di Coworking Legian. Thanks mas Mik.
